server:
  port: 9001
spring:
  application:
    name: mobile-service
feign:
  hystrix:
    enabled: true
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://center1:8081/eureka/,http://center2:8082/eureka/